---
# TODO(gib): Work out whether we even need these files
# This is currently just sample code from other apps, we probably won't need
# all or any of it.
stages:
- name: <%= appname %>
  inputs:
  - type: git
    branch: master
  jobs:
  - name: Ant build
    type: builder
    artifact_dir: output
    build_type: ant
    script: |-
      #!/bin/bash
      ant
- name: Security Scanning
  inputs:
  - type: job
    stage: Package Application
    job: Ant build
  triggers:
  - type: stage
  properties:
  - name: SLACK_WEBHOOK_PATH
    value: https://hooks.slack.com/services/
    type: text
  jobs:
  - name: Static code analysis
    type: tester
    fail_stage: false
    extension_id: ibm.devops.services.pipeline.appscan.static.builder
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    SETUP_SERVICE_SPACE: 'true'
    WAIT_TIME: '10'
- name: Deploy Stage
  inputs:
  - type: job
    stage: Package Application
    job: Ant build
  triggers:
  - type: stage
  properties:
  - name: SLACK_WEBHOOK_PATH
    value: T03T7PX58/B067X25CJ/I9gxU8ys9j39YLui7Ol8fajO
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf push "${CF_APP}"
